#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vsftpd[-1]
	add ucitrack vsftpd
	set ucitrack.@vsftpd[-1].init=vsftpd
	commit ucitrack
EOF

chmod 0755 /usr/share/vsftpd/*.sh
cat > /etc/vsftpd.conf <<EOF
check_shell=NO
background=YES
listen=NO
listen_port=21
ftp_data_port=20
listen_ipv6=YES
local_enable=YES
write_enable=NO
download_enable=YES
local_root=/mnt
local_umask=022
file_open_mode=0755
ftp_username=ftp
anonymous_enable=YES
no_anon_password=YES
anon_world_readable_only=YES
anon_upload_enable=YES
anon_mkdir_write_enable=NO
anon_other_write_enable=NO
anon_umask=022
anon_root=/var/ftp
chown_uploads=YES
chown_username=ftp
EOF

rm -rf /tmp/luci-modulecache /tmp/luci-indexcache
exit 0

